# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Regression Model Evaluation

In [4]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv('/content/drive/MyDrive/decision-tree/housing (1).csv', header=None, delimiter=r"\s+", names=column_names)

In [ ]:
"""
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's"""

"\nCRIM - per capita crime rate by town\nZN - proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS - proportion of non-retail business acres per town.\nCHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)\nNOX - nitric oxides concentration (parts per 10 million)\nRM - average number of rooms per dwelling\nAGE - proportion of owner-occupied units built prior to 1940\nDIS - weighted distances to five Boston employment centres\nRAD - index of accessibility to radial highways\nTAX - full-value property-tax rate per $10,000\nPTRATIO - pupil-teacher ratio by town\nB - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT - % lower status of the population\nMEDV - Median value of owner-occupied homes in $1000's"

In [ ]:
data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [7]:
# Your code here :
from sklearn.model_selection import train_test_split
train_data, test_data = train_test_split(data, test_size=0.2)
train_x, train_y = train_data.drop(columns="MEDV"), train_data["MEDV"]
test_x, test_y = test_data.drop(columns="MEDV"), test_data["MEDV"]

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [8]:
# Your code here :
from sklearn.linear_model import LinearRegression
regr = LinearRegression()
regr.fit(train_x, train_y)
train_pred = regr.predict(train_x)
test_pred = regr.predict(test_x)

## 3. Calculate and print R-squared for both the training and the testing set.

In [10]:
# Your code here :
from sklearn.metrics import r2_score
train_r2 = r2_score(train_y, train_pred)
test_r2 = r2_score(test_y, test_pred)
print(f"Train R2: {train_r2}")
print(f"Test R2: {test_r2}")

Train R2: 0.7507309676695155
Test R2: 0.6834421256433189

## 4. Calculate and print mean squared error for both the training and the testing set.

In [11]:
# Your code here :
from sklearn.metrics import mean_squared_error
train_mse = mean_squared_error(train_y, train_pred)
test_mse = mean_squared_error(test_y, test_pred)
print(f"Train MSE: {train_mse}")
print(f"Test MSE: {test_mse}")

Train MSE: 21.310025258626787
Test MSE: 25.37456509719443

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [12]:
# Your code here :
from sklearn.metrics import mean_absolute_error
train_mae = mean_absolute_error(train_y, train_pred)
test_mae = mean_absolute_error(test_y, test_pred)
print(f"Train MAE: {train_mae}")
print(f"Test MAE: {test_mae}")

Train MAE: 3.2031436749549145
Test MAE: 3.424262757496142

## Classification Model Evaluation

In [13]:
from sklearn.datasets import load_iris
data = load_iris()

In [14]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

In [15]:
column_names = data.feature_names

In [17]:
df = pd.DataFrame(data['data'],columns=column_names)

In [18]:
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [19]:
target = pd.DataFrame(data.target)

In [20]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [21]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [47]:
# Your code here :
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(df, data.target, test_size=0.2)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [49]:
# Your code here :
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(X_train, Y_train)

LogisticRegression()

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [50]:
# Your code here :
from sklearn.metrics import accuracy_score
train_acc = accuracy_score(Y_train, clf.predict(X_train))
test_acc = accuracy_score(Y_test, clf.predict(X_test))
print(f"Train Accuracy: {train_acc}")
print(f"Test Accuracy: {test_acc}")

Train Accuracy: 0.9666666666666667
Test Accuracy: 1.0

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [52]:
# Your code here :
from sklearn.metrics import balanced_accuracy_score
train_bal_acc = balanced_accuracy_score(Y_train, clf.predict(X_train))
test_bal_acc = balanced_accuracy_score(Y_test, clf.predict(X_test))
print(f"Train Balanced Accuracy: {train_bal_acc}")
print(f"Test Balanced Accuracy: {test_bal_acc}")

Train Balanced Accuracy: 0.9661084529505581
Test Balanced Accuracy: 1.0

## 10. Calculate and print the precision score for both the training and the testing set.

In [53]:
# Your code here :
from sklearn.metrics import precision_score
train_prec = precision_score(Y_train, clf.predict(X_train), average='weighted')
test_prec = precision_score(Y_test, clf.predict(X_test), average='weighted')
print(f"Train Precision: {train_prec}")
print(f"Test Precision: {test_prec}")

Train Precision: 0.9672906602254429
Test Precision: 1.0

## 11. Calculate and print the recall score for both the training and the testing set.

In [58]:
# Your code here :
from sklearn.metrics import recall_score
train_rec = recall_score(Y_train, clf.predict(X_train), average='weighted')
test_rec = recall_score(Y_test, clf.predict(X_test), average='weighted')
print(f"Train Recall: {train_rec}")
print(f"Test Recall: {test_rec}")

Train Recall: 0.9666666666666667
Test Recall: 1.0

## 12. Calculate and print the F1 score for both the training and the testing set.

In [55]:
# Your code here :
from sklearn.metrics import f1_score
train_f1 = f1_score(Y_train, clf.predict(X_train), average='weighted')
test_f1 = f1_score(Y_test, clf.predict(X_test), average='weighted')
print(f"Train F1: {train_f1}")
print(f"Test F1: {test_f1}")

Train F1: 0.9665865865865866
Test F1: 1.0

## 13. Generate confusion matrices for both the training and the testing set.

In [56]:
# Your code here :
from sklearn.metrics import confusion_matrix
train_cm = confusion_matrix(Y_train, clf.predict(X_train))
test_cm = confusion_matrix(Y_test, clf.predict(X_test))
print(f"Train Confusion Matrix:\n{train_cm}")
print(f"Test Confusion Matrix:\n{test_cm}")

Train Confusion Matrix:
[[38  0  0]
 [ 0 35  3]
 [ 0  1 43]]
Test Confusion Matrix:
[[12  0  0]
 [ 0 12  0]
 [ 0  0  6]]

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [ ]:
# Have fun here !